spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: Azazazru228
    driver-class-name: org.postgresql.Driver
  security:
    basic:
      enabled: false
  data:
    redis:
      host: redis
      port: 6379
  app:
    jwt:
      secret: "supersecretkeysupersecretkey123456"
      expirationMillis: 2592000000
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: ERROR
    com.example: INFO
