spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: Azazazru228
    driver-class-name: org.postgresql.Driver
  security:
    basic:
      enabled: false
  data:
    redis:
      host: redis
      port: 6379
  logging:
    level:
      root: INFO
      com.example: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  app:
    jwt:
      secret: "supersecretkeysupersecretkey123456"
      expirationMillis: 2592000000

