spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: Azazazru228
    driver-class-name: org.postgresql.Driver
  security:
    basic:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG
      org.hibernate: DEBUG
      com.example: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} [%X{activeProfile}] - %msg%n"
  app:
    jwt:
      secret: "supersecretkeysupersecretkey123456"
      expirationMillis: 2592000000